import type { ServiceCategory, Professional, Booking, ChatThread, User } from './types';

export const mockUser: User = {
  id: 'user-1',
  name: 'Priya Menon',
  phone: '+91 98765 43210',
  avatar: '/images/user-avatar.jpg',
  addresses: [
    {
      id: 'addr-1',
      label: 'Home',
      full: '42, 4th Cross, Jayanagar 4th Block, Bangalore - 560011',
      lat: 12.9279,
      lng: 77.5831,
    },
  ],
};

export const mockCategories: ServiceCategory[] = [
  {
    id: 'tailoring',
    name: 'Tailoring',
    icon: 'Scissors',
    color: '#FF6B5B',
    description: 'Saree stitching, blouse design, embroidery',
    services: [
      { id: 'saree-stitch', categoryId: 'tailoring', name: 'Saree Stitching', price: 350, priceUnit: 'per saree', description: 'Complete saree fall and edging stitching', estimatedTime: '1-2 days' },
      { id: 'blouse-design', categoryId: 'tailoring', name: 'Blouse Design & Stitch', price: 500, priceUnit: 'per blouse', description: 'Custom blouse with fitting and design', estimatedTime: '2-3 days' },
      { id: 'embroidery', categoryId: 'tailoring', name: 'Embroidery Work', price: 200, priceUnit: 'per design', description: 'Zari, aari, maggam, and hand embroidery', estimatedTime: '3-5 days' },
      { id: 'alteration', categoryId: 'tailoring', name: 'Alterations', price: 150, priceUnit: 'per item', description: 'Size changes, repairs, adjustments', estimatedTime: 'Same day' },
      { id: 'fall-padding', categoryId: 'tailoring', name: 'Fall & Padding', price: 250, priceUnit: 'per saree', description: 'Saree fall attachment and padding', estimatedTime: '1 day' },
      { id: 'ironing', categoryId: 'tailoring', name: 'Premium Ironing', price: 30, priceUnit: 'per item', description: 'Steam ironing for sarees and blouses', estimatedTime: 'Same day' },
    ],
  },
  {
    id: 'laundry',
    name: 'Laundry',
    icon: 'Droplets',
    color: '#3B82F6',
    description: 'Washing, ironing, dry cleaning',
    services: [
      { id: 'wash-fold', categoryId: 'laundry', name: 'Wash & Fold', price: 80, priceUnit: 'per kg', description: 'Machine wash and fold', estimatedTime: '1 day' },
      { id: 'dry-clean', categoryId: 'laundry', name: 'Dry Cleaning', price: 200, priceUnit: 'per item', description: 'Premium dry cleaning', estimatedTime: '2-3 days' },
      { id: 'steam-iron', categoryId: 'laundry', name: 'Steam Ironing', price: 40, priceUnit: 'per item', description: 'Professional steam press', estimatedTime: 'Same day' },
      { id: 'shoe-cleaning', categoryId: 'laundry', name: 'Shoe Cleaning', price: 180, priceUnit: 'per pair', description: 'Deep clean and deodorize sneakers and formal shoes', estimatedTime: '1 day' },
      { id: 'curtain-cleaning', categoryId: 'laundry', name: 'Curtain Cleaning', price: 120, priceUnit: 'per panel', description: 'Pickup, wash, dry, and steam finish curtains', estimatedTime: '2 days' },
    ],
  },
  {
    id: 'plumbing',
    name: 'Plumbing',
    icon: 'Wrench',
    color: '#06B6D4',
    description: 'Leak repair, installation, drainage',
    services: [
      { id: 'leak-repair', categoryId: 'plumbing', name: 'Leak Repair', price: 300, priceUnit: 'per job', description: 'Fix taps, pipes, and toilet leaks', estimatedTime: 'Same day' },
      { id: 'installation', categoryId: 'plumbing', name: 'Installation', price: 500, priceUnit: 'per job', description: 'New fixture and fitting installation', estimatedTime: '1 day' },
      { id: 'drain-cleaning', categoryId: 'plumbing', name: 'Drain Cleaning', price: 450, priceUnit: 'per job', description: 'Clear kitchen, bathroom, and balcony drain blocks', estimatedTime: 'Same day' },
      { id: 'water-motor', categoryId: 'plumbing', name: 'Water Motor Repair', price: 650, priceUnit: 'per visit', description: 'Pump inspection, repair, and replacement support', estimatedTime: 'Same day' },
    ],
  },
  {
    id: 'electrical',
    name: 'Electrical',
    icon: 'Zap',
    color: '#F59E0B',
    description: 'Wiring, fittings, inverter repair',
    services: [
      { id: 'wiring', categoryId: 'electrical', name: 'Wiring & Fittings', price: 400, priceUnit: 'per job', description: 'New points, switches, and wiring', estimatedTime: '1-2 days' },
      { id: 'fan-install', categoryId: 'electrical', name: 'Fan/Light Install', price: 250, priceUnit: 'per item', description: 'Ceiling fan and light fixture install', estimatedTime: 'Same day' },
      { id: 'inverter-service', categoryId: 'electrical', name: 'Inverter Service', price: 550, priceUnit: 'per visit', description: 'Battery, inverter, and backup wiring checks', estimatedTime: 'Same day' },
      { id: 'switchboard-repair', categoryId: 'electrical', name: 'Switchboard Repair', price: 300, priceUnit: 'per board', description: 'Loose switch, socket, and MCB panel fixes', estimatedTime: 'Same day' },
    ],
  },
  {
    id: 'carpentry',
    name: 'Carpentry',
    icon: 'Hammer',
    color: '#8B5CF6',
    description: 'Furniture repair, woodwork, modular',
    services: [
      { id: 'furniture-repair', categoryId: 'carpentry', name: 'Furniture Repair', price: 450, priceUnit: 'per job', description: 'Chair, table, and door repairs', estimatedTime: '1-2 days' },
      { id: 'modular-kitchen', categoryId: 'carpentry', name: 'Modular Setup', price: 5000, priceUnit: 'per project', description: 'Custom modular kitchen carpentry', estimatedTime: '5-7 days' },
      { id: 'door-lock-repair', categoryId: 'carpentry', name: 'Door & Lock Repair', price: 350, priceUnit: 'per job', description: 'Door alignment, hinges, handles, and locks', estimatedTime: 'Same day' },
      { id: 'wall-shelves', categoryId: 'carpentry', name: 'Wall Shelves', price: 800, priceUnit: 'per set', description: 'Measurement and installation of compact shelves', estimatedTime: '1-2 days' },
    ],
  },
  {
    id: 'daily-labour',
    name: 'One Day Workers',
    icon: 'BriefcaseBusiness',
    color: '#10B981',
    description: 'Daily helpers for shifting, cleaning, loading, and shop work',
    services: [
      { id: 'one-day-helper', categoryId: 'daily-labour', name: 'One Day Helper', price: 700, priceUnit: 'per day', description: 'Verified worker for household or shop support', estimatedTime: '1 day' },
      { id: 'loading-helper', categoryId: 'daily-labour', name: 'Loading Helper', price: 850, priceUnit: 'per day', description: 'Loading, unloading, and shifting support', estimatedTime: '1 day' },
      { id: 'event-helper', categoryId: 'daily-labour', name: 'Event Helper', price: 900, priceUnit: 'per day', description: 'Temporary helpers for events, stores, and stalls', estimatedTime: '1 day' },
      { id: 'shop-helper', categoryId: 'daily-labour', name: 'Shop Helper', price: 750, priceUnit: 'per day', description: 'Billing support, shelf stocking, and local errands', estimatedTime: '1 day' },
    ],
  },
  {
    id: 'construction-labour',
    name: 'Construction Labour',
    icon: 'HardHat',
    color: '#F97316',
    description: 'Masons, painters, helpers, and site labour teams',
    services: [
      { id: 'site-helper', categoryId: 'construction-labour', name: 'Site Labour', price: 900, priceUnit: 'per day', description: 'Daily construction labour for site work', estimatedTime: '1 day' },
      { id: 'mason-helper', categoryId: 'construction-labour', name: 'Mason Helper', price: 1100, priceUnit: 'per day', description: 'Masonry, plastering, and material movement support', estimatedTime: '1 day' },
      { id: 'painting-helper', categoryId: 'construction-labour', name: 'Painting Helper', price: 950, priceUnit: 'per day', description: 'Wall preparation, masking, and painter support', estimatedTime: '1 day' },
      { id: 'tile-helper', categoryId: 'construction-labour', name: 'Tile Helper', price: 1200, priceUnit: 'per day', description: 'Tile cutting, adhesive mixing, and site cleanup', estimatedTime: '1 day' },
    ],
  },
  {
    id: 'cleaning',
    name: 'Cleaning',
    icon: 'Sparkles',
    color: '#14B8A6',
    description: 'Deep cleaning, kitchen, bathroom, sofa, and move-in cleaning',
    services: [
      { id: 'home-deep-clean', categoryId: 'cleaning', name: 'Home Deep Cleaning', price: 1800, priceUnit: 'per home', description: 'Full home cleaning with kitchen, bathroom, and floors', estimatedTime: '4-6 hours' },
      { id: 'bathroom-clean', categoryId: 'cleaning', name: 'Bathroom Cleaning', price: 399, priceUnit: 'per bathroom', description: 'Tiles, fixtures, floor, and stain removal', estimatedTime: '1 hour' },
      { id: 'kitchen-clean', categoryId: 'cleaning', name: 'Kitchen Cleaning', price: 799, priceUnit: 'per kitchen', description: 'Counter, chimney exterior, sink, floor, and cabinet exterior', estimatedTime: '2 hours' },
      { id: 'sofa-clean', categoryId: 'cleaning', name: 'Sofa Cleaning', price: 650, priceUnit: 'per sofa', description: 'Vacuum, shampoo, and fabric-safe sofa cleaning', estimatedTime: '1-2 hours' },
    ],
  },
  {
    id: 'ac-repair',
    name: 'AC Repair',
    icon: 'Snowflake',
    color: '#0EA5E9',
    description: 'AC service, gas refill, installation, and cooling repair',
    services: [
      { id: 'ac-service', categoryId: 'ac-repair', name: 'AC Service', price: 599, priceUnit: 'per AC', description: 'Filter, coil, and outdoor unit basic service', estimatedTime: '1 hour' },
      { id: 'ac-gas-refill', categoryId: 'ac-repair', name: 'Gas Refill', price: 1800, priceUnit: 'per AC', description: 'Leak check and refrigerant top-up', estimatedTime: '2 hours' },
      { id: 'ac-install', categoryId: 'ac-repair', name: 'AC Installation', price: 1499, priceUnit: 'per AC', description: 'Split AC installation with standard fitting support', estimatedTime: '2-3 hours' },
    ],
  },
  {
    id: 'painting',
    name: 'Painting',
    icon: 'Paintbrush',
    color: '#F97316',
    description: 'Wall painting, touch-ups, texture, and waterproofing',
    services: [
      { id: 'wall-painting', categoryId: 'painting', name: 'Wall Painting', price: 12, priceUnit: 'per sq ft', description: 'Interior wall painting with surface preparation', estimatedTime: '1-3 days' },
      { id: 'texture-paint', categoryId: 'painting', name: 'Texture Painting', price: 45, priceUnit: 'per sq ft', description: 'Feature wall texture and pattern painting', estimatedTime: '1-2 days' },
      { id: 'waterproofing', categoryId: 'painting', name: 'Waterproofing', price: 35, priceUnit: 'per sq ft', description: 'Leak-prone wall and terrace waterproof coating', estimatedTime: '1-2 days' },
    ],
  },
  {
    id: 'appliance-repair',
    name: 'Appliance Repair',
    icon: 'Plug',
    color: '#6366F1',
    description: 'Washing machine, fridge, microwave, and chimney service',
    services: [
      { id: 'washing-machine', categoryId: 'appliance-repair', name: 'Washing Machine Repair', price: 499, priceUnit: 'per visit', description: 'Inspection and repair for front/top-load machines', estimatedTime: 'Same day' },
      { id: 'fridge-repair', categoryId: 'appliance-repair', name: 'Fridge Repair', price: 599, priceUnit: 'per visit', description: 'Cooling, compressor, and thermostat inspection', estimatedTime: 'Same day' },
      { id: 'microwave-repair', categoryId: 'appliance-repair', name: 'Microwave Repair', price: 449, priceUnit: 'per visit', description: 'Heating, plate, and panel troubleshooting', estimatedTime: 'Same day' },
    ],
  },
  {
    id: 'pest-control',
    name: 'Pest Control',
    icon: 'Bug',
    color: '#84CC16',
    description: 'Cockroach, termite, mosquito, and general pest treatment',
    services: [
      { id: 'cockroach-control', categoryId: 'pest-control', name: 'Cockroach Control', price: 999, priceUnit: 'per treatment', description: 'Gel and spray treatment for kitchen and bathrooms', estimatedTime: '1 hour' },
      { id: 'termite-control', categoryId: 'pest-control', name: 'Termite Control', price: 2500, priceUnit: 'per visit', description: 'Wood and wall termite inspection and treatment', estimatedTime: '2-4 hours' },
      { id: 'mosquito-control', categoryId: 'pest-control', name: 'Mosquito Control', price: 799, priceUnit: 'per treatment', description: 'Indoor and outdoor mosquito reduction treatment', estimatedTime: '1 hour' },
    ],
  },
];

export const allServices = mockCategories.flatMap(c => c.services);

const baseProfessionals: Professional[] = [
  {
    id: 'tailor-1',
    name: 'Lakshmi Devi',
    avatar: '/images/tailor-1.jpg',
    category: 'tailoring',
    services: ['saree-stitch', 'blouse-design', 'embroidery', 'alteration', 'fall-padding', 'ironing'],
    rating: 4.9,
    reviewCount: 234,
    experience: 15,
    tier: 'platinum',
    verified: true,
    priceRange: '\u20b9200-800',
    about: 'Expert in bridal blouse designs and maggam embroidery. 15 years of experience serving 5000+ happy customers. Specializes in silk saree handling and custom fitting.',
    portfolio: ['/images/tailor-1.jpg', '/images/progress-finished.jpg', '/images/progress-stitched.jpg', '/images/tailor-3.jpg'],
    availability: 'Available today',
    location: 'Jayanagar, Bangalore',
    distance: '1.2 km',
    reviews: [
      { id: 'rev-1', userName: 'Ananya R.', avatar: '', rating: 5, text: 'Absolutely stunning work on my wedding blouse! The maggam embroidery was even better than I imagined. Perfect fit on the first try.', date: '2 days ago', beforeImage: '/images/progress-measured.jpg', afterImage: '/images/progress-finished.jpg' },
      { id: 'rev-2', userName: 'Meera K.', avatar: '', rating: 5, text: 'Lakshmi ji understood exactly what I wanted for my silk saree fall. Very professional and delivered on time.', date: '1 week ago' },
      { id: 'rev-3', userName: 'Sunita P.', avatar: '', rating: 4, text: 'Great work on alterations. Quick turnaround and reasonable pricing. Will definitely book again.', date: '2 weeks ago' },
    ],
  },
  {
    id: 'tailor-2',
    name: 'Ramesh Kumar',
    avatar: '/images/tailor-2.jpg',
    category: 'tailoring',
    services: ['saree-stitch', 'blouse-design', 'embroidery', 'alteration', 'fall-padding'],
    rating: 4.7,
    reviewCount: 189,
    experience: 12,
    tier: 'gold',
    verified: true,
    priceRange: '\u20b9150-600',
    about: 'Specialist in zari work and traditional embroidery patterns. Known for precision cutting and perfect finishing. Works with all fabric types.',
    portfolio: ['/images/tailor-2.jpg', '/images/progress-cut.jpg', '/images/progress-stitched.jpg'],
    availability: 'Next slot: Tomorrow',
    location: 'Malleshwaram, Bangalore',
    distance: '3.5 km',
    reviews: [
      { id: 'rev-4', userName: 'Kavita S.', avatar: '', rating: 5, text: 'The zari work on my blouse was exquisite. Ramesh ji has magic hands!', date: '3 days ago' },
    ],
  },
  {
    id: 'tailor-3',
    name: 'Priya Sharma',
    avatar: '/images/tailor-3.jpg',
    category: 'tailoring',
    services: ['saree-stitch', 'blouse-design', 'alteration', 'ironing'],
    rating: 4.8,
    reviewCount: 156,
    experience: 8,
    tier: 'gold',
    verified: true,
    priceRange: '\u20b9100-500',
    about: 'Young designer with modern aesthetic. Great for fusion wear and contemporary blouse designs. Quick turnaround time.',
    portfolio: ['/images/tailor-3.jpg', '/images/progress-finished.jpg'],
    availability: 'Available today',
    location: 'Koramangala, Bangalore',
    distance: '2.1 km',
    reviews: [],
  },
  {
    id: 'plumber-1',
    name: 'Rajesh P.',
    avatar: '/images/plumber-1.jpg',
    category: 'plumbing',
    services: ['leak-repair', 'installation'],
    rating: 4.6,
    reviewCount: 98,
    experience: 10,
    tier: 'gold',
    verified: true,
    priceRange: '\u20b9200-1000',
    about: 'Licensed plumber with 10+ years experience. Quick response for emergencies. All work guaranteed.',
    portfolio: ['/images/plumber-1.jpg'],
    availability: 'Available today',
    location: 'JP Nagar, Bangalore',
    distance: '1.8 km',
    reviews: [],
  },
  {
    id: 'electrician-1',
    name: 'Suresh K.',
    avatar: '/images/electrician-1.jpg',
    category: 'electrical',
    services: ['wiring', 'fan-install'],
    rating: 4.8,
    reviewCount: 142,
    experience: 12,
    tier: 'platinum',
    verified: true,
    priceRange: '\u20b9250-1500',
    about: 'Certified electrician. Specializes in home wiring and inverter systems. Safety-first approach.',
    portfolio: ['/images/electrician-1.jpg'],
    availability: 'Next slot: Tomorrow',
    location: 'BTM Layout, Bangalore',
    distance: '2.4 km',
    reviews: [],
  },
  {
    id: 'laundry-1',
    name: 'CleanWash Pro',
    avatar: '/images/laundry-1.jpg',
    category: 'laundry',
    services: ['wash-fold', 'dry-clean', 'steam-iron'],
    rating: 4.5,
    reviewCount: 312,
    experience: 5,
    tier: 'silver',
    verified: true,
    priceRange: '\u20b950-500',
    about: 'Professional laundry service with pickup and delivery. Uses eco-friendly detergents.',
    portfolio: ['/images/laundry-1.jpg'],
    availability: 'Available today',
    location: 'HSR Layout, Bangalore',
    distance: '0.8 km',
    reviews: [],
  },
  {
    id: 'tailor-4',
    name: 'Anita Rao',
    avatar: '/images/tailor-1.jpg',
    category: 'tailoring',
    services: ['saree-stitch', 'blouse-design', 'alteration'],
    rating: 4.7,
    reviewCount: 118,
    experience: 11,
    tier: 'gold',
    verified: true,
    priceRange: '\u20b9150-550',
    about: 'Detailed fittings, quick alternations, and polished finishing for daily and festive wear.',
    portfolio: ['/images/tailor-1.jpg'],
    availability: 'Available today',
    location: 'Indiranagar, Bangalore',
    distance: '2.7 km',
    reviews: [],
  },
  {
    id: 'tailor-5',
    name: 'Nisha Mehta',
    avatar: '/images/tailor-2.jpg',
    category: 'tailoring',
    services: ['embroidery', 'fall-padding', 'ironing'],
    rating: 4.6,
    reviewCount: 96,
    experience: 9,
    tier: 'silver',
    verified: true,
    priceRange: '\u20b9100-420',
    about: 'Precision embroidery and soft-finish saree support for event and office wear.',
    portfolio: ['/images/tailor-2.jpg'],
    availability: 'Next slot: Tomorrow',
    location: 'Jayanagar, Bangalore',
    distance: '1.1 km',
    reviews: [],
  },
  {
    id: 'laundry-2',
    name: 'SparkClean Laundry',
    avatar: '/images/laundry-1.jpg',
    category: 'laundry',
    services: ['wash-fold', 'dry-clean'],
    rating: 4.6,
    reviewCount: 180,
    experience: 7,
    tier: 'gold',
    verified: true,
    priceRange: '\u20b960-420',
    about: 'Fast pickup, careful sorting, and steam finishing for family laundry.',
    portfolio: ['/images/laundry-1.jpg'],
    availability: 'Available today',
    location: 'Koramangala, Bangalore',
    distance: '1.6 km',
    reviews: [],
  },
  {
    id: 'laundry-3',
    name: 'FreshFold Studio',
    avatar: '/images/laundry-1.jpg',
    category: 'laundry',
    services: ['wash-fold', 'steam-iron'],
    rating: 4.5,
    reviewCount: 141,
    experience: 6,
    tier: 'silver',
    verified: true,
    priceRange: '\u20b950-300',
    about: 'Daily laundry support with tidy folding and express iron service.',
    portfolio: ['/images/laundry-1.jpg'],
    availability: 'Next slot: Tomorrow',
    location: 'HSR Layout, Bangalore',
    distance: '2.9 km',
    reviews: [],
  },
  {
    id: 'laundry-4',
    name: 'Urban Wash Hub',
    avatar: '/images/laundry-1.jpg',
    category: 'laundry',
    services: ['dry-clean', 'steam-iron'],
    rating: 4.8,
    reviewCount: 210,
    experience: 8,
    tier: 'platinum',
    verified: true,
    priceRange: '\u20b9100-500',
    about: 'Premium dry cleaning, garment care, and pickup coordination for busy homes.',
    portfolio: ['/images/laundry-1.jpg'],
    availability: 'Available today',
    location: 'Bellandur, Bangalore',
    distance: '3.3 km',
    reviews: [],
  },
  {
    id: 'plumber-2',
    name: 'PipeSafe Crew',
    avatar: '/images/plumber-1.jpg',
    category: 'plumbing',
    services: ['leak-repair', 'installation'],
    rating: 4.7,
    reviewCount: 110,
    experience: 9,
    tier: 'gold',
    verified: true,
    priceRange: '\u20b9250-850',
    about: 'Leak tracing, tap swaps, and drain fixes with quick turnaround.',
    portfolio: ['/images/plumber-1.jpg'],
    availability: 'Available today',
    location: 'BTM Layout, Bangalore',
    distance: '2.2 km',
    reviews: [],
  },
  {
    id: 'plumber-3',
    name: 'AquaFix Works',
    avatar: '/images/plumber-1.jpg',
    category: 'plumbing',
    services: ['leak-repair'],
    rating: 4.5,
    reviewCount: 84,
    experience: 8,
    tier: 'silver',
    verified: true,
    priceRange: '\u20b9200-700',
    about: 'Efficient plumbing support for homes and small stores.',
    portfolio: ['/images/plumber-1.jpg'],
    availability: 'Next slot: Tomorrow',
    location: 'JP Nagar, Bangalore',
    distance: '1.9 km',
    reviews: [],
  },
  {
    id: 'plumber-4',
    name: 'FlowMaster Services',
    avatar: '/images/plumber-1.jpg',
    category: 'plumbing',
    services: ['installation'],
    rating: 4.8,
    reviewCount: 132,
    experience: 13,
    tier: 'platinum',
    verified: true,
    priceRange: '\u20b9300-1000',
    about: 'Bathroom fittings, kitchen waterline work, and pressure fixes.',
    portfolio: ['/images/plumber-1.jpg'],
    availability: 'Available today',
    location: 'Whitefield, Bangalore',
    distance: '4.1 km',
    reviews: [],
  },
  {
    id: 'electrician-2',
    name: 'VoltCare Team',
    avatar: '/images/electrician-1.jpg',
    category: 'electrical',
    services: ['wiring', 'fan-install'],
    rating: 4.7,
    reviewCount: 126,
    experience: 10,
    tier: 'gold',
    verified: true,
    priceRange: '\u20b9250-900',
    about: 'Home wiring, fan installation, and clean switchboard upgrades.',
    portfolio: ['/images/electrician-1.jpg'],
    availability: 'Available today',
    location: 'Marathahalli, Bangalore',
    distance: '3.0 km',
    reviews: [],
  },
  {
    id: 'electrician-3',
    name: 'SparkLine Electric',
    avatar: '/images/electrician-1.jpg',
    category: 'electrical',
    services: ['fan-install'],
    rating: 4.6,
    reviewCount: 93,
    experience: 7,
    tier: 'silver',
    verified: true,
    priceRange: '\u20b9200-650',
    about: 'Quick electrical fixes for lights, fans, and socket replacements.',
    portfolio: ['/images/electrician-1.jpg'],
    availability: 'Next slot: Tomorrow',
    location: 'Jayanagar, Bangalore',
    distance: '1.4 km',
    reviews: [],
  },
  {
    id: 'electrician-4',
    name: 'BrightCircuit',
    avatar: '/images/electrician-1.jpg',
    category: 'electrical',
    services: ['wiring'],
    rating: 4.8,
    reviewCount: 150,
    experience: 14,
    tier: 'platinum',
    verified: true,
    priceRange: '\u20b9300-1200',
    about: 'Full electrical setup for homes, shops, and renovation work.',
    portfolio: ['/images/electrician-1.jpg'],
    availability: 'Available today',
    location: 'Electronic City, Bangalore',
    distance: '5.0 km',
    reviews: [],
  },
  {
    id: 'carpentry-1',
    name: 'WoodCraft Studio',
    avatar: '/images/service-carpentry.jpg',
    category: 'carpentry',
    services: ['furniture-repair', 'modular-kitchen'],
    rating: 4.7,
    reviewCount: 88,
    experience: 12,
    tier: 'gold',
    verified: true,
    priceRange: '\u20b9300-2000',
    about: 'Furniture repair, shelves, and compact modular work for homes.',
    portfolio: ['/images/service-carpentry.jpg'],
    availability: 'Available today',
    location: 'Koramangala, Bangalore',
    distance: '2.5 km',
    reviews: [],
  },
  {
    id: 'carpentry-2',
    name: 'HomeFix Carpentry',
    avatar: '/images/service-carpentry.jpg',
    category: 'carpentry',
    services: ['furniture-repair'],
    rating: 4.5,
    reviewCount: 76,
    experience: 8,
    tier: 'silver',
    verified: true,
    priceRange: '\u20b9250-1400',
    about: 'Door tuning, wardrobe fixes, and durable wood finish support.',
    portfolio: ['/images/service-carpentry.jpg'],
    availability: 'Next slot: Tomorrow',
    location: 'Indiranagar, Bangalore',
    distance: '2.0 km',
    reviews: [],
  },
  {
    id: 'carpentry-3',
    name: 'Moduluxe Makers',
    avatar: '/images/service-carpentry.jpg',
    category: 'carpentry',
    services: ['modular-kitchen'],
    rating: 4.8,
    reviewCount: 119,
    experience: 15,
    tier: 'platinum',
    verified: true,
    priceRange: '\u20b94500-9000',
    about: 'Bespoke kitchen modules, storage design, and premium installation.',
    portfolio: ['/images/service-carpentry.jpg'],
    availability: 'Available today',
    location: 'Whitefield, Bangalore',
    distance: '4.5 km',
    reviews: [],
  },
  {
    id: 'carpentry-4',
    name: 'CraftNest Works',
    avatar: '/images/service-carpentry.jpg',
    category: 'carpentry',
    services: ['furniture-repair'],
    rating: 4.6,
    reviewCount: 64,
    experience: 6,
    tier: 'silver',
    verified: true,
    priceRange: '\u20b9200-1000',
    about: 'Small repair jobs, panels, and custom wood pieces on demand.',
    portfolio: ['/images/service-carpentry.jpg'],
    availability: 'Available today',
    location: 'HSR Layout, Bangalore',
    distance: '3.6 km',
    reviews: [],
  },
  {
    id: 'daily-labour-1',
    name: 'Ravi Daily Helper',
    avatar: '/images/service-daily-labour.jpg',
    category: 'daily-labour',
    services: ['one-day-helper', 'loading-helper'],
    rating: 4.6,
    reviewCount: 72,
    experience: 5,
    tier: 'silver',
    verified: true,
    priceRange: '\u20b9700-900',
    about: 'Reliable one-day worker for home shifting, shop support, loading, unloading, and cleaning help.',
    portfolio: ['/images/service-daily-labour.jpg'],
    availability: 'Available today',
    location: 'Jayanagar, Bangalore',
    distance: '0.9 km',
    reviews: [],
  },
  {
    id: 'construction-labour-1',
    name: 'Bharat Site Labour Team',
    avatar: '/images/service-construction-labour.jpg',
    category: 'construction-labour',
    services: ['site-helper', 'mason-helper'],
    rating: 4.7,
    reviewCount: 105,
    experience: 9,
    tier: 'gold',
    verified: true,
    priceRange: '\u20b9900-1500',
    about: 'Construction labour team for plastering, painting support, material movement, and daily site work.',
    portfolio: ['/images/service-construction-labour.jpg'],
    availability: 'Available today',
    location: 'JP Nagar, Bangalore',
    distance: '1.7 km',
    reviews: [],
  },
  {
    id: 'cleaning-1',
    name: 'NeatNest Cleaning',
    avatar: '/images/service-cleaning.jpg',
    category: 'cleaning',
    services: ['home-deep-clean', 'bathroom-clean', 'kitchen-clean', 'sofa-clean'],
    rating: 4.8,
    reviewCount: 168,
    experience: 6,
    tier: 'gold',
    verified: true,
    priceRange: '\u20b9399-1800',
    about: 'Deep cleaning team for apartments, kitchens, bathrooms, and sofa care with same-day slots.',
    portfolio: ['/images/service-cleaning.jpg'],
    availability: 'Available today',
    location: 'Jayanagar, Bangalore',
    distance: '1.0 km',
    reviews: [],
  },
  {
    id: 'ac-repair-1',
    name: 'CoolAir Experts',
    avatar: '/images/service-ac-repair.jpg',
    category: 'ac-repair',
    services: ['ac-service', 'ac-gas-refill', 'ac-install'],
    rating: 4.7,
    reviewCount: 143,
    experience: 9,
    tier: 'gold',
    verified: true,
    priceRange: '\u20b9599-1800',
    about: 'AC service, gas refill, and installation crew with clean workmanship and fast diagnosis.',
    portfolio: ['/images/service-ac-repair.jpg'],
    availability: 'Available today',
    location: 'BTM Layout, Bangalore',
    distance: '2.6 km',
    reviews: [],
  },
  {
    id: 'painting-1',
    name: 'ColorCraft Painters',
    avatar: '/images/service-painting.jpg',
    category: 'painting',
    services: ['wall-painting', 'texture-paint', 'waterproofing'],
    rating: 4.6,
    reviewCount: 97,
    experience: 11,
    tier: 'silver',
    verified: true,
    priceRange: '\u20b912-45',
    about: 'Interior wall painting, texture finishes, touch-ups, and waterproofing for compact homes.',
    portfolio: ['/images/service-painting.jpg'],
    availability: 'Next slot: Tomorrow',
    location: 'Koramangala, Bangalore',
    distance: '2.8 km',
    reviews: [],
  },
  {
    id: 'appliance-1',
    name: 'FixIt Appliance Care',
    avatar: '/images/service-appliance-repair.jpg',
    category: 'appliance-repair',
    services: ['washing-machine', 'fridge-repair', 'microwave-repair'],
    rating: 4.7,
    reviewCount: 121,
    experience: 8,
    tier: 'gold',
    verified: true,
    priceRange: '\u20b9449-999',
    about: 'Appliance repair for washing machines, refrigerators, and microwaves with transparent visits.',
    portfolio: ['/images/service-appliance-repair.jpg'],
    availability: 'Available today',
    location: 'HSR Layout, Bangalore',
    distance: '3.1 km',
    reviews: [],
  },
  {
    id: 'pest-1',
    name: 'SafeHome Pest Control',
    avatar: '/images/service-pest-control.jpg',
    category: 'pest-control',
    services: ['cockroach-control', 'termite-control', 'mosquito-control'],
    rating: 4.5,
    reviewCount: 88,
    experience: 7,
    tier: 'silver',
    verified: true,
    priceRange: '\u20b9799-2500',
    about: 'Pest treatment for apartments and shops with odor-controlled options and follow-up guidance.',
    portfolio: ['/images/service-pest-control.jpg'],
    availability: 'Available today',
    location: 'Indiranagar, Bangalore',
    distance: '3.8 km',
    reviews: [],
  },
];

const categoryImages: Record<string, string[]> = {
  tailoring: ['/images/tailor-1.jpg', '/images/tailor-2.jpg', '/images/tailor-3.jpg', '/images/service-tailoring.jpg', '/images/progress-finished.jpg'],
  laundry: ['/images/laundry-1.jpg', '/images/service-laundry.jpg', '/images/progress-stitched.jpg', '/images/user-avatar.jpg'],
  plumbing: ['/images/plumber-1.jpg', '/images/service-plumbing.jpg', '/images/electrician-1.jpg', '/images/user-avatar.jpg'],
  electrical: ['/images/electrician-1.jpg', '/images/service-electrical.jpg', '/images/plumber-1.jpg', '/images/user-avatar.jpg'],
  carpentry: ['/images/service-carpentry.jpg', '/images/plumber-1.jpg', '/images/tailor-3.jpg', '/images/progress-cut.jpg'],
  'daily-labour': ['/images/service-daily-labour.jpg', '/images/plumber-1.jpg', '/images/electrician-1.jpg', '/images/user-avatar.jpg'],
  'construction-labour': ['/images/service-construction-labour.jpg', '/images/electrician-1.jpg', '/images/plumber-1.jpg', '/images/progress-cut.jpg'],
  cleaning: ['/images/service-cleaning.jpg', '/images/laundry-1.jpg', '/images/progress-finished.jpg', '/images/user-avatar.jpg'],
  'ac-repair': ['/images/service-ac-repair.jpg', '/images/electrician-1.jpg', '/images/plumber-1.jpg', '/images/user-avatar.jpg'],
  painting: ['/images/service-painting.jpg', '/images/tailor-2.jpg', '/images/progress-finished.jpg', '/images/progress-stitched.jpg'],
  'appliance-repair': ['/images/service-appliance-repair.jpg', '/images/plumber-1.jpg', '/images/electrician-1.jpg', '/images/user-avatar.jpg'],
  'pest-control': ['/images/service-pest-control.jpg', '/images/laundry-1.jpg', '/images/tailor-3.jpg', '/images/user-avatar.jpg'],
};

const categoryNamePools: Record<string, string[]> = {
  tailoring: ['Meena Designs', 'Asha Stitch Studio', 'Kiran Boutique', 'Zari Queen Tailors', 'Naveen Fashion Fit', 'Sridevi Needle Works', 'Farah Custom Fits', 'Anjali Alteration Care', 'Devika Bridal Stitch', 'Sameera Saree Studio', 'Ritu Needle House', 'Maya Silk Finish', 'Pooja Pattern Works', 'Leela Embroidery Pro', 'Kavya Fit Lab', 'Nandini Boutique Pro', 'Varsha Blouse Works', 'Rekha Hemming Hub', 'Sana Festival Stitch', 'Uma Tailor Pro'],
  laundry: ['QuickFold Care', 'WhiteCloud Laundry', 'SteamPro Wash', 'FreshPress Hub', 'EcoWash Team', 'DailySpin Laundry', 'Neha Fresh Fold', 'Arjun Dry Clean', 'Sana Steam Care', 'Ravi Wash Works', 'Aditi Garment Care', 'Imran Press Point', 'Pallavi Curtain Care', 'Kumar Shoe Clean', 'Maya Linen Studio', 'Rohit Express Iron', 'Tara Family Laundry', 'Nikhil Wardrobe Care', 'Priya Clean Basket', 'Urban Fresh Team'],
  plumbing: ['TapFix Kumar', 'PipeCare Team', 'WaterLine Pros', 'LeakStop Ravi', 'BathFit Services', 'DrainClear Crew', 'Nadeem Pipe Works', 'Sanjay Water Motor', 'Firoz Faucet Care', 'Mohan Drain Doctor', 'Vikram Bath Repair', 'Rakesh Flow Fix', 'Amit Tank Line', 'Saira Plumbing Pro', 'Harish Kitchen Tap', 'Deepak Pump Care', 'Iqbal Leak Finder', 'Prakash Pipe Pro', 'Manoj WaterLine', 'Karthik Quick Plumb'],
  electrical: ['PowerSafe Arun', 'LightFix Team', 'WireWell Services', 'SwitchPro Kiran', 'HomeVolt Crew', 'BrightHome Electric', 'Suresh Circuit Care', 'Anil Fan Fittings', 'Naveen Inverter Pro', 'Rahul Socket Works', 'Deepa Safety Check', 'Farhan Wiring Hub', 'Madan MCB Care', 'Rohit Light Line', 'Kavita Home Volt', 'Ajay Power Point', 'Girish Switch Care', 'Leena Bright Fix', 'Yusuf Electric Pro', 'Vijay Wire Doctor'],
  carpentry: ['ShelfMate Works', 'DoorFit Raju', 'WoodLine Studio', 'CabinetCare Team', 'HomeWood Makers', 'Urban Joinery', 'Prakash Wood Works', 'Ramesh Door Care', 'Nisha Modular Studio', 'Sunil Shelf Pro', 'Imran Lock Fit', 'Mohan Polish Works', 'Geeta Furniture Care', 'Kiran Kitchen Wood', 'Amit Wardrobe Repair', 'Harsha Hinge Fix', 'Sameer Custom Wood', 'Varun Panel Works', 'Lakshmi Cabinet Care', 'Arif Carpenter Pro'],
  'daily-labour': ['Manjunath Helper', 'DayWork Team', 'ShiftMate Crew', 'Local Helper Pro', 'StoreSupport Ravi', 'QuickHands Team', 'Suresh Loading Help', 'Fatima Home Helper', 'Raju One Day Pro', 'Anita Shop Support', 'Kumar Event Helper', 'Noor Quick Hands', 'Vijay Errand Worker', 'Saira Packing Help', 'Mohan Shift Support', 'Deepak Local Worker', 'Meena Day Helper', 'Imran Stock Support', 'Harish Box Moving', 'Pooja Work Assist'],
  'construction-labour': ['BuildMate Crew', 'MasonLine Team', 'SiteReady Workers', 'TileSupport Pros', 'PlasterCare Team', 'StrongSite Labour', 'Ramesh Mason Helper', 'Kiran Site Crew', 'Farhan Tile Support', 'Mahesh Brick Line', 'Anita Site Assist', 'Ravi Cement Team', 'Sanjay Plaster Works', 'Noor Build Support', 'Vikram Rod Helper', 'Deepa Paint Prep', 'Amit Sand Team', 'Mohan Floor Crew', 'Suresh Site Pro', 'Arif Construction Help'],
  cleaning: ['ShineHome Crew', 'KitchenSpark Team', 'BathroomFresh Pros', 'MoveIn Cleaners', 'SofaCare Studio', 'NeatDay Services', 'Asha Deep Clean', 'Rohit Glass Care', 'Meera Kitchen Pro', 'Imran Sofa Clean', 'Nisha Bathroom Care', 'Tara Floor Polish', 'Kumar Move-In Clean', 'Sana Dust Care', 'Leela Home Shine', 'Vijay Balcony Wash', 'Farah Fridge Clean', 'Mohan Tile Scrub', 'Pooja House Care', 'Urban Neat Team'],
  'ac-repair': ['CoolFix Team', 'ChillCare Experts', 'ACLine Services', 'FrostPro Repair', 'AirFlow Kumar', 'ClimateCare Crew', 'Suresh Cooling Pro', 'Nadeem AC Doctor', 'Ravi Split Service', 'Kiran Gas Refill', 'Amit Air Care', 'Farhan Cool Line', 'Prakash Filter Clean', 'Leena Climate Fix', 'Manoj AC Install', 'Yusuf Fan Coil Care', 'Harish Compressor Check', 'Deepak CoolPoint', 'Maya AC Support', 'Vikram AirFlow Pro'],
  painting: ['WallGlow Painters', 'TexturePro Team', 'ColorLine Crew', 'WaterSeal Works', 'FreshCoat Studio', 'PaintMate Pros', 'Raju Wall Finish', 'Nisha Color Care', 'Sanjay Texture Works', 'Imran Paint Line', 'Asha Home Colors', 'Kumar Waterproof Pro', 'Farah Feature Wall', 'Mohan Spray Finish', 'Leela Touch-Up Care', 'Vijay Putty Prep', 'Anil Fresh Coat', 'Pooja Color Match', 'Rohit Wall Care', 'Arif Paint Crew'],
  'appliance-repair': ['MachineCare Ravi', 'FridgeFix Team', 'MicroPro Services', 'WasherLine Crew', 'HomeAppliance Care', 'FixSmart Experts', 'Suresh Appliance Pro', 'Nadeem Cooling Check', 'Kavita Machine Care', 'Amit Microwave Fix', 'Farhan Fridge Care', 'Meena Washer Works', 'Rohit Chimney Service', 'Imran Oven Repair', 'Prakash Mixer Care', 'Sana HomeFix Tech', 'Vijay Dryer Repair', 'Kiran Smart Repair', 'Anil Kitchen Appliance', 'Leela Gadget Care'],
  'pest-control': ['BugSafe Team', 'TermiteGuard Pros', 'MosquitoShield Care', 'SafeNest Control', 'PestLine Services', 'CleanHome Shield', 'Ravi Roach Control', 'Nisha Termite Care', 'Farhan Pest Guard', 'Asha Mosquito Pro', 'Kumar Bedbug Care', 'Sana Safe Spray', 'Mohan Wood Shield', 'Leela Kitchen Guard', 'Imran Pest Check', 'Pooja Home Shield', 'Vijay Herbal Spray', 'Noor Apartment Care', 'Rohit Pest Doctor', 'Urban Bug Care'],
};

const locations = [
  'Jayanagar, Bangalore',
  'JP Nagar, Bangalore',
  'Koramangala, Bangalore',
  'HSR Layout, Bangalore',
  'Indiranagar, Bangalore',
  'BTM Layout, Bangalore',
  'Whitefield, Bangalore',
  'Malleshwaram, Bangalore',
  'Electronic City, Bangalore',
  'Marathahalli, Bangalore',
];

function createDemoProfessional(category: ServiceCategory, index: number): Professional {
  const serviceIds = category.services.map((service) => service.id);
  const imagePool = categoryImages[category.id] || ['/images/user-avatar.jpg'];
  const namePool = categoryNamePools[category.id] || [`${category.name} Pro`];
  const avatar = imagePool[index % imagePool.length];
  const baseName = namePool[index % namePool.length];
  const rating = Number((4.4 + ((index % 6) * 0.1)).toFixed(1));
  const minPrice = Math.max(50, category.services[0]?.price || 250);
  const maxPrice = Math.max(minPrice + 250, category.services.at(-1)?.price || minPrice + 500);

  return {
    id: `${category.id}-demo-${index + 1}`,
    name: index < namePool.length ? baseName : `${baseName} ${Math.floor(index / namePool.length) + 1}`,
    avatar,
    category: category.id,
    services: serviceIds.slice(0, Math.min(serviceIds.length, 4)),
    rating,
    reviewCount: 70 + index * 13,
    experience: 3 + (index % 14),
    tier: index % 5 === 0 ? 'platinum' : index % 2 === 0 ? 'gold' : 'silver',
    verified: true,
    priceRange: `\u20b9${minPrice}-${maxPrice}`,
    about: `Verified ${category.name.toLowerCase()} professional with local experience, clear pricing, and quick service updates.`,
    portfolio: [avatar, ...imagePool.filter((image) => image !== avatar)].slice(0, 3),
    availability: index % 3 === 0 ? 'Next slot: Tomorrow' : 'Available today',
    location: locations[index % locations.length],
    distance: `${(0.7 + index * 0.23).toFixed(1)} km`,
    reviews: [],
  };
}

function withMinimumProfessionalsPerSector(minimum = 20): Professional[] {
  const professionals = [...baseProfessionals];

  mockCategories.forEach((category) => {
    const existingCount = professionals.filter((professional) => professional.category === category.id).length;
    for (let index = existingCount; index < minimum; index += 1) {
      professionals.push(createDemoProfessional(category, index));
    }
  });

  return professionals;
}

export const mockProfessionals: Professional[] = withMinimumProfessionalsPerSector(20);

export const mockBookings: Booking[] = [
  {
    id: 'book-1',
    serviceId: 'blouse-design',
    serviceName: 'Blouse Design & Stitch',
    categoryId: 'tailoring',
    professionalId: 'tailor-1',
    professionalName: 'Lakshmi Devi',
    professionalAvatar: '/images/tailor-1.jpg',
    customerId: 'user-1',
    status: 'in_progress',
    scheduledDate: '2026-07-04',
    scheduledTime: '11:00 AM',
    price: 650,
    address: mockUser.addresses[0],
    notes: 'Boat neck, elbow sleeves, maggam embroidery on back',
    progressPhotos: [
      { id: 'prog-1', stage: 'measured', image: '/images/progress-measured.jpg', caption: 'Measurements taken perfectly', timestamp: 'July 3, 10:30 AM' },
      { id: 'prog-2', stage: 'cut', image: '/images/progress-cut.jpg', caption: 'Fabric cut with precision', timestamp: 'July 3, 2:15 PM' },
      { id: 'prog-3', stage: 'stitched', image: '/images/progress-stitched.jpg', caption: 'Stitching in progress \u2014 70% done', timestamp: 'July 4, 9:00 AM' },
    ],
    paymentStatus: 'advance_paid',
    paymentAmount: 325,
    createdAt: '2026-07-02',
  },
  {
    id: 'book-2',
    serviceId: 'leak-repair',
    serviceName: 'Leak Repair',
    categoryId: 'plumbing',
    professionalId: 'plumber-1',
    professionalName: 'Rajesh P.',
    professionalAvatar: '/images/plumber-1.jpg',
    customerId: 'user-1',
    status: 'confirmed',
    scheduledDate: '2026-07-05',
    scheduledTime: '02:00 PM',
    price: 400,
    address: mockUser.addresses[0],
    notes: 'Kitchen tap leaking continuously',
    progressPhotos: [],
    paymentStatus: 'pending',
    paymentAmount: 0,
    createdAt: '2026-07-03',
  },
  {
    id: 'book-4',
    serviceId: 'one-day-helper',
    serviceName: 'One Day Helper',
    categoryId: 'daily-labour',
    professionalId: 'daily-labour-1',
    professionalName: 'Ravi Daily Helper',
    professionalAvatar: '/images/plumber-1.jpg',
    customerId: 'user-1',
    status: 'confirmed',
    scheduledDate: '2026-07-04',
    scheduledTime: '09:00 AM',
    price: 749,
    address: mockUser.addresses[0],
    notes: 'Need one worker for shifting boxes and shop cleaning for one day',
    progressPhotos: [],
    paymentStatus: 'advance_paid',
    paymentAmount: 350,
    createdAt: '2026-07-03',
  },
  {
    id: 'book-5',
    serviceId: 'site-helper',
    serviceName: 'Site Labour',
    categoryId: 'construction-labour',
    professionalId: 'construction-labour-1',
    professionalName: 'Bharat Site Labour Team',
    professionalAvatar: '/images/electrician-1.jpg',
    customerId: 'user-1',
    status: 'in_progress',
    scheduledDate: '2026-07-04',
    scheduledTime: '08:00 AM',
    price: 1200,
    address: mockUser.addresses[0],
    notes: 'Two workers needed for plastering material movement and site cleanup',
    progressPhotos: [],
    paymentStatus: 'advance_paid',
    paymentAmount: 600,
    createdAt: '2026-07-03',
  },
  {
    id: 'book-3',
    serviceId: 'saree-stitch',
    serviceName: 'Saree Stitching',
    categoryId: 'tailoring',
    professionalId: 'tailor-3',
    professionalName: 'Priya Sharma',
    professionalAvatar: '/images/tailor-3.jpg',
    customerId: 'user-1',
    status: 'completed',
    scheduledDate: '2026-07-01',
    scheduledTime: '10:00 AM',
    price: 400,
    address: mockUser.addresses[0],
    notes: 'New kanjeevaram saree, need fall and edges',
    progressPhotos: [],
    paymentStatus: 'completed',
    paymentAmount: 400,
    createdAt: '2026-06-30',
  },
];

export const mockChatThreads: ChatThread[] = [
  {
    id: 'chat-1',
    professionalId: 'tailor-1',
    professionalName: 'Lakshmi Devi',
    professionalAvatar: '/images/tailor-1.jpg',
    serviceName: 'Blouse Design',
    lastMessage: 'The embroidery is almost done. Will send photos soon!',
    lastMessageTime: '10:30 AM',
    unread: 2,
    messages: [
      { id: 'msg-1', senderId: 'user-1', senderName: 'Priya Menon', senderAvatar: '/images/user-avatar.jpg', text: 'Hi Lakshmi ji, I wanted to check on my blouse progress', timestamp: '10:00 AM', type: 'text' },
      { id: 'msg-2', senderId: 'tailor-1', senderName: 'Lakshmi Devi', senderAvatar: '/images/tailor-1.jpg', text: "Hello! Yes, it's going great. The cutting is done and I've started on the embroidery.", timestamp: '10:15 AM', type: 'text' },
      { id: 'msg-3', senderId: 'tailor-1', senderName: 'Lakshmi Devi', senderAvatar: '/images/tailor-1.jpg', text: 'The embroidery is almost done. Will send photos soon!', timestamp: '10:30 AM', type: 'text' },
    ],
  },
  {
    id: 'chat-2',
    professionalId: 'plumber-1',
    professionalName: 'Rajesh P.',
    professionalAvatar: '/images/plumber-1.jpg',
    serviceName: 'Leak Repair',
    lastMessage: "I'll bring the new tap connector. See you tomorrow.",
    lastMessageTime: 'Yesterday',
    unread: 0,
    messages: [
      { id: 'msg-4', senderId: 'user-1', senderName: 'Priya Menon', senderAvatar: '/images/user-avatar.jpg', text: 'Hi, is 2 PM tomorrow still good?', timestamp: 'Yesterday', type: 'text' },
      { id: 'msg-5', senderId: 'plumber-1', senderName: 'Rajesh P.', senderAvatar: '/images/plumber-1.jpg', text: "Yes, perfect. I'll bring the new tap connector. See you tomorrow.", timestamp: 'Yesterday', type: 'text' },
    ],
  },
];

mockChatThreads.push(
  {
    id: 'chat-3',
    professionalId: 'laundry-1',
    professionalName: 'CleanWash Pro',
    professionalAvatar: '/images/laundry-1.jpg',
    serviceName: 'Wash & Fold',
    lastMessage: 'Your clothes are packed and ready for delivery by 6 PM.',
    lastMessageTime: '9:45 AM',
    unread: 1,
    messages: [
      { id: 'msg-6', senderId: 'user-1', senderName: 'Priya Menon', senderAvatar: '/images/user-avatar.jpg', text: 'Can you pick up the laundry before noon?', timestamp: '8:20 AM', type: 'text' },
      { id: 'msg-7', senderId: 'laundry-1', senderName: 'CleanWash Pro', senderAvatar: '/images/laundry-1.jpg', text: 'Yes, pickup is scheduled between 11 and 11:30 AM.', timestamp: '8:31 AM', type: 'text' },
      { id: 'msg-8', senderId: 'laundry-1', senderName: 'CleanWash Pro', senderAvatar: '/images/laundry-1.jpg', text: 'Your clothes are packed and ready for delivery by 6 PM.', timestamp: '9:45 AM', type: 'text' },
    ],
  },
  {
    id: 'chat-4',
    professionalId: 'electrician-1',
    professionalName: 'Suresh K.',
    professionalAvatar: '/images/electrician-1.jpg',
    serviceName: 'Fan/Light Install',
    lastMessage: 'I will bring the ladder, tester, and new screws.',
    lastMessageTime: '8:15 AM',
    unread: 0,
    messages: [
      { id: 'msg-9', senderId: 'user-1', senderName: 'Priya Menon', senderAvatar: '/images/user-avatar.jpg', text: 'The ceiling fan is already delivered. Do I need to arrange anything else?', timestamp: '8:02 AM', type: 'text' },
      { id: 'msg-10', senderId: 'electrician-1', senderName: 'Suresh K.', senderAvatar: '/images/electrician-1.jpg', text: 'No, I will bring the ladder, tester, and new screws.', timestamp: '8:15 AM', type: 'text' },
    ],
  },
  {
    id: 'chat-5',
    professionalId: 'cleaning-1',
    professionalName: 'NeatNest Cleaning',
    professionalAvatar: '/images/laundry-1.jpg',
    serviceName: 'Home Deep Cleaning',
    lastMessage: 'Two cleaners will arrive with machine scrubber and supplies.',
    lastMessageTime: 'Yesterday',
    unread: 3,
    messages: [
      { id: 'msg-11', senderId: 'user-1', senderName: 'Priya Menon', senderAvatar: '/images/user-avatar.jpg', text: 'Please focus on kitchen shelves and both bathrooms.', timestamp: 'Yesterday', type: 'text' },
      { id: 'msg-12', senderId: 'cleaning-1', senderName: 'NeatNest Cleaning', senderAvatar: '/images/laundry-1.jpg', text: 'Noted. We will cover kitchen shelves, chimney exterior, tiles, taps, and floor stains.', timestamp: 'Yesterday', type: 'text' },
      { id: 'msg-13', senderId: 'cleaning-1', senderName: 'NeatNest Cleaning', senderAvatar: '/images/laundry-1.jpg', text: 'Two cleaners will arrive with machine scrubber and supplies.', timestamp: 'Yesterday', type: 'text' },
    ],
  },
  {
    id: 'chat-6',
    professionalId: 'ac-repair-1',
    professionalName: 'CoolAir Experts',
    professionalAvatar: '/images/electrician-1.jpg',
    serviceName: 'AC Service',
    lastMessage: 'Cooling test will take about 20 minutes after cleaning.',
    lastMessageTime: 'Mon',
    unread: 0,
    messages: [
      { id: 'msg-14', senderId: 'user-1', senderName: 'Priya Menon', senderAvatar: '/images/user-avatar.jpg', text: 'The AC is cooling slowly. Can you check the gas also?', timestamp: 'Mon', type: 'text' },
      { id: 'msg-15', senderId: 'ac-repair-1', senderName: 'CoolAir Experts', senderAvatar: '/images/electrician-1.jpg', text: 'Yes, we will clean filters, check coil condition, and test gas pressure.', timestamp: 'Mon', type: 'text' },
      { id: 'msg-16', senderId: 'ac-repair-1', senderName: 'CoolAir Experts', senderAvatar: '/images/electrician-1.jpg', text: 'Cooling test will take about 20 minutes after cleaning.', timestamp: 'Mon', type: 'text' },
    ],
  },
  {
    id: 'chat-7',
    professionalId: 'daily-labour-1',
    professionalName: 'Ravi Daily Helper',
    professionalAvatar: '/images/plumber-1.jpg',
    serviceName: 'One Day Helper',
    lastMessage: 'I can stay till 6 PM if the shifting takes longer.',
    lastMessageTime: 'Sun',
    unread: 1,
    messages: [
      { id: 'msg-17', senderId: 'user-1', senderName: 'Priya Menon', senderAvatar: '/images/user-avatar.jpg', text: 'Need help moving boxes from ground floor to second floor.', timestamp: 'Sun', type: 'text' },
      { id: 'msg-18', senderId: 'daily-labour-1', senderName: 'Ravi Daily Helper', senderAvatar: '/images/plumber-1.jpg', text: 'Okay. Please keep the boxes taped and marked if anything is fragile.', timestamp: 'Sun', type: 'text' },
      { id: 'msg-19', senderId: 'daily-labour-1', senderName: 'Ravi Daily Helper', senderAvatar: '/images/plumber-1.jpg', text: 'I can stay till 6 PM if the shifting takes longer.', timestamp: 'Sun', type: 'text' },
    ],
  },
  {
    id: 'chat-8',
    professionalId: 'painting-1',
    professionalName: 'ColorCraft Painters',
    professionalAvatar: '/images/tailor-2.jpg',
    serviceName: 'Wall Painting',
    lastMessage: 'I will share two shade options after checking the wall.',
    lastMessageTime: 'Sat',
    unread: 0,
    messages: [
      { id: 'msg-20', senderId: 'user-1', senderName: 'Priya Menon', senderAvatar: '/images/user-avatar.jpg', text: 'The living room wall has damp patches near the window.', timestamp: 'Sat', type: 'text' },
      { id: 'msg-21', senderId: 'painting-1', senderName: 'ColorCraft Painters', senderAvatar: '/images/tailor-2.jpg', text: 'We should inspect before painting. Waterproof primer may be needed.', timestamp: 'Sat', type: 'text' },
      { id: 'msg-22', senderId: 'painting-1', senderName: 'ColorCraft Painters', senderAvatar: '/images/tailor-2.jpg', text: 'I will share two shade options after checking the wall.', timestamp: 'Sat', type: 'text' },
    ],
  },
  {
    id: 'chat-9',
    professionalId: 'appliance-1',
    professionalName: 'FixIt Appliance Care',
    professionalAvatar: '/images/plumber-1.jpg',
    serviceName: 'Washing Machine Repair',
    lastMessage: 'Please keep the machine empty before the visit.',
    lastMessageTime: 'Fri',
    unread: 2,
    messages: [
      { id: 'msg-23', senderId: 'user-1', senderName: 'Priya Menon', senderAvatar: '/images/user-avatar.jpg', text: 'The washing machine stops after filling water.', timestamp: 'Fri', type: 'text' },
      { id: 'msg-24', senderId: 'appliance-1', senderName: 'FixIt Appliance Care', senderAvatar: '/images/plumber-1.jpg', text: 'It may be a sensor or drain issue. I will inspect both.', timestamp: 'Fri', type: 'text' },
      { id: 'msg-25', senderId: 'appliance-1', senderName: 'FixIt Appliance Care', senderAvatar: '/images/plumber-1.jpg', text: 'Please keep the machine empty before the visit.', timestamp: 'Fri', type: 'text' },
    ],
  },
  {
    id: 'chat-10',
    professionalId: 'pest-1',
    professionalName: 'SafeHome Pest Control',
    professionalAvatar: '/images/tailor-3.jpg',
    serviceName: 'Cockroach Control',
    lastMessage: 'Keep kitchen shelves empty for best treatment coverage.',
    lastMessageTime: 'Thu',
    unread: 0,
    messages: [
      { id: 'msg-26', senderId: 'user-1', senderName: 'Priya Menon', senderAvatar: '/images/user-avatar.jpg', text: 'I need pest control mainly for kitchen and utility area.', timestamp: 'Thu', type: 'text' },
      { id: 'msg-27', senderId: 'pest-1', senderName: 'SafeHome Pest Control', senderAvatar: '/images/tailor-3.jpg', text: 'We will use gel treatment for cabinets and spray for corners.', timestamp: 'Thu', type: 'text' },
      { id: 'msg-28', senderId: 'pest-1', senderName: 'SafeHome Pest Control', senderAvatar: '/images/tailor-3.jpg', text: 'Keep kitchen shelves empty for best treatment coverage.', timestamp: 'Thu', type: 'text' },
    ],
  },
);
